version: 2.1

jobs:
  docker-build:
    machine:
      image: ubuntu-2204:2024.11.1
    steps:
      - checkout
      - run:
          name: "Build docker image"
          command: "docker build -t badge9416/app:latest ."
      - run:
          name: "Run docker container"
          command: "docker run -d -p 8080:8080 badge9416/app:latest"
      - run:
          name: "Wait for docker up"
          command: "sleep 5"
      - run:
          name: "Test docker container"
          command: 'curl -f http://localhost:8080 || (echo "App is not responding" && exit 1)'
      - run:
          name: "Push Docker image"
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push badge9416/app:latest

workflows:
  docker-build-workflow:
    jobs:
      - docker-build