name: Docker Build and Publish

on:
  push:
    branches:
      - master

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t badge9416/app:latest .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 --name app-container badge9416/app:latest
          sleep 5

      - name: Test Docker container
        run: |
          curl -f http://localhost:8080 || (echo "App is not responding" && exit 1)

      - name: Push Docker image
        run: |
          docker push badge9416/app:latest